name: growgrail
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.0.2
  firebase_core: ^3.2.0
  uganda_mobile_money: ^0.0.5
  permission_handler: ^11.3.1
  flutterwave_standard: ^1.0.8
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  uuid: ^4.4.2
  firebase_authentication: ^0.0.28
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  uuid: ^3.0.5
  firebase_authentication: ^0.0.28
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  firebase_messaging: ^15.0.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/money.jpg
    - assets/images/person4.webp
    - assets/images/person3.webp
    - assets/images/car.webp
    - assets/images/GGlogo.png
    - assets/images/moneygrow.jpg
    - assets/images/.env 
    

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
